language: c
install: wget https://raw.githubusercontent.com/yomimono/ocaml-ci-scripts/extra-env/.travis-docker.sh #fork needed for extra_env, github pr#160
script: bash -ex .travis-docker.sh
sudo: required
services:
  - docker
sudo: false
env:
 global:
   - PRE_INSTALL_HOOK="cd /home/opam/opam-repository && git pull origin master && opam update -u -y"
   - POST_INSTALL_HOOK="sh ./.travis-ci.sh"
   - PINS="mirage:. mirage-types:. mirage-types-lwt:. mirage-runtime:."
   - TESTS=false #testing via travis-ci.sh
 matrix:
   - PACKAGE=mirage DISTRO=debian-testing OCAML_VERSION=4.03.0 EXTRA_ENV="MODE=xen"
   - PACKAGE=mirage DISTRO=debian-testing OCAML_VERSION=4.03.0 EXTRA_ENV="MODE=ukvm"
   - PACKAGE=mirage DISTRO=debian-unstable OCAML_VERSION=4.03.0 EXTRA_ENV="MODE=unix"
   - PACKAGE=mirage DISTRO=ubuntu-16.04 OCAML_VERSION=4.03.0 EXTRA_ENV="MODE=virtio"
   - PACKAGE=mirage DISTRO=centos-7 OCAML_VERSION=4.03.0 EXTRA_ENV="MODE=xen"
   - PACKAGE=mirage DISTRO=centos-7 OCAML_VERSION=4.03.0 EXTRA_ENV="MODE=ukvm"
   - PACKAGE=mirage DISTRO=debian-testing OCAML_VERSION=4.04.0 EXTRA_ENV="MODE=xen"
   - PACKAGE=mirage DISTRO=ubuntu-16.04 OCAML_VERSION=4.04.0 EXTRA_ENV="MODE=ukvm"
   - PACKAGE=mirage DISTRO=centos-7 OCAML_VERSION=4.04.0 EXTRA_ENV="MODE=virtio"
